// export const domain = "https://api.eplatform.online/api/v1/";
// export const domainHub = "https://api.eplatform.online/";
export const domain = "http://localhost/api/v1/";
export const domainHub = "http://localhost/";

export const environment = {
    SignUpAPI: domain + "auth/register",
    SignInAPI: domain + "auth/login",
    RefreshJWTTokenAPI: domain + "token/refresh",
    RevokeJWTTokenAPI: domain + "token/revoke",
    RegisterConfirmAPI: domain + "token/check-authenticated-and-refresh",
    ResetPasswordAPI: domain + "auth/reset-password",
    ForgotPasswordAPI: domain + "auth/forgot-password",
    ConfirmRecoveryPassword: domain + "auth/confirm-recovery-verifycode",
    GetRoles: domain + "admin/roles",
    CreateRole: domain + "admin/roles/add",
    DeleteRole: domain + "admin/roles/delete/",
    UpdateRole: domain + "admin/roles/update/",
    GetRoleById: domain + "admin/roles/",
    AddRoleClaim: domain + "admin/roles/",
    DeleteRoleClaim: domain + "admin/roles/",
    UpdateRoleClaim: domain + "admin/roles/",
    GetUsers: domain + "users/",
    CreateUser: domain + "users/create",
    LockOrUnlockUser: domain + "users/lock-or-unlock-user",
    GetUserById: domain + "users/",
    SettingRoleOfUser: domain + "users/",
    SuggestionOfUser: domain + "users/suggest?SearchString=",
    Shop: domain + "shops/",
    Categories: domain + "categories",
    WarehouseForSelect: domain + "utilities/ware-houses-for-select",
    AddProduct: domain + "shops/",
    UpdateProduct: domain + "products/",
    DeleteProduct: domain + "products/",
    Province: domain + "vietnameese-location/provinces",
    District: domain + "vietnameese-location/districts/",
    Ward: domain + "vietnameese-location/wards/",
    getCategoriesInHome: domain + "categories-in-home",
    HotProduct: domain + "product-items/hot-products",
    TodaySuggestion: domain + "product-items/today-suggestions",
    getProductDetail: domain + "product-items/",
    addToCart: domain + "carts/add-to-cart",
    getCartItems: domain + "carts",
    createOrder: domain + "orders/create-order",
    getCartNum: domain + "carts/get-cart-number",
    getAllStatuses: domain + "orders/get-all-status",
    changeOrderStauts: domain + "orders/change-order-status",
    getOrderById: domain + "orders/",
    getPurchaseOrders: domain + "orders/purchase-orders",
    cancelOrder: domain + "orders/cancel-order/",
    notification: domainHub + "api/notification-hub",
    searchProduct: domain + "products/search",
    increaseProductSearchFrequency: domain + "products/increase-search-frequences",
    getSuggestions: domain + "products/autocomplete",
    checkRoleAPI: domain + "token/check-authorization",
};
