server {
    listen 80;
    server_name api.eplatform.online;
    if ($cloudflare_https != "on") {
        return 301 https://$host$request_uri;
    }

    # Proxy to back-end API
    location /api/ {
        limit_req zone=one burst=10 nodelay;
        proxy_pass http://eplatform_api:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass $http_upgrade;
    }

    location /swagger/ {
        proxy_pass http://eplatform_api:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}