version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eplatform_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mssql
      - redis
      - mongodb
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - backend
  
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: mssql
    environment:
      - SA_PASSWORD=@Sinh123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_DATABASE=EcommercePlatform
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - mssql_data:/var/opt/mssql

  redis:
    image: "redis:latest"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
  
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongodb_data:/data/db

networks:
  backend:
    driver: bridge

volumes:
  mssql_data:
  mongodb_data: